### ISSUE TITLE
Move repositories to Beautiful Atoms organization

### ISSUE THREAD

**Issue by superstar54** [beautiful-atoms/beautiful-atoms#110]
I created a Github organization: Beautiful-Atoms

https://github.com/beautiful-atoms

This organization is supposed to host:
- beautiful-atoms
- beautiful-atoms-api
- beautiful-atoms-doc
- Other beautiful atoms plugins

Problem
==========
The free account has limited features and storage (https://github.com/pricing). Thus, we need sponsors to upgrade the organization. When upgraded, we can start to transfer the repositories to the organization.

**Comment by superstar54** [comment]
Good news! I applied for an educational benefit using the email of the university. The organization is upgraded to the "Team Plan" for free.

@alchem0x2A @uliaschauer Let's move the repositories?

**Comment by alchem0x2A** [comment]
yes definitely worth doing the move!

**Comment by superstar54** [comment]
Done
