### ISSUE TITLE
[Enhancement] Move blender docker image to a better place

### ISSUE THREAD

**Issue by alchem0x2A** [beautiful-atoms/beautiful-atoms#112]
Currently the container image (hosted on docker) is using my personal account, maybe better to host it on github container registry. https://docs.github.com/cn/packages/working-with-a-github-packages-registry/working-with-the-container-registry so that it can have a better naming. Can look into how-to but most likely need @superstar54 to set the variables.

**Comment by superstar54** [comment]
Please let me know when needing me to set the variables.

**Comment by alchem0x2A** [comment]
disable docker image build for PR seems necessary. We can limit the build & push actions only to limited branches (e.g. main and develop) so that PRs won't be messed up by failing actions
