### ISSUE TITLE
draw unit cell and update it with geometry node

### ISSUE THREAD

**Issue by superstar54** [beautiful-atoms/beautiful-atoms#12]
The unit cell is a line and can not be rendered. Every time, a draw_cell() function has to be called before rendering. Besides, the draw_cell() function has to be called to update the cell.

Proposal solution
==================
Represent unit cell as a mesh. Update the mesh using the transfer attributes function in Geometry nodes.

**Comment by jkstartt** [comment]
I know its not your ideal solution, but in the meantime could provide a quick example/tutorial of how to use the draw_cell() function like this?

**Comment by superstar54** [comment]
Hi, you can use ```cell.draw()``` to draw the cell for rendering.

Here is an example of an FCC Au structure.

``` python
from batoms.build import bulk
from batoms.utils.butils import removeAll, set_world
from batoms import Batoms
removeAll()
au = bulk('au', 'Au', cubic=True)
au.cell.draw()
set_world(color=[0.2, 0.2, 0.2, 1.0])
draw_plane(location=[0, 0, -au.size[0]], size=200, color=(0.9, 0.9, 0.9, 1))
au.render.viewport = [1, -0.3, 0.3]
au.render.engine = 'cycles'
au.render.lights['Default'].type = 'POINT'
au.render.lights['Default'].lock_light_to_camera = False
au.render.lights['Default'].energy = 50000
au.render.lights['Default'].location = [10, 4, 10]
au.get_image(output='au_cell.png')
```

This is the final image:

<img src="https://user-images.githubusercontent.com/11457659/163348819-5bc0c12b-9acd-4de7-8afc-571607764027.png" width = 300 />
