### ISSUE TITLE
whenever i using the batoms  ,the blender crashes 

### ISSUE THREAD

**Issue by lwjjie** [beautiful-atoms/beautiful-atoms#183]
**Describe the bug**
whenever i using the batoms  ,the blender crashes 
**To Reproduce**
i install the batoms refering to https://beautiful-atoms.readthedocs.io/en/latest/getting_started/installing/windows.html#id1
**Expected behavior**
such as the example :
from batoms import Batoms
h2o = Batoms('h2o', species = ['O', 'H', 'H'], positions= [[0, 0, 0.40],[0, -0.76, -0.2], [0, 0.76, -0.2]])

**Desktop:**
 - Windows 

**Blender Version**
- 3.3

**Comment by alchem0x2A** [comment]
Some api change in blender 3.3 breaks batoms. You can switch to version 3.2. The compatibility issue will be fixed in a future PR.

**Comment by lwjjie** [comment]
Thank you sincerely！
I will give it a try and report back in time.

**Comment by lwjjie** [comment]
I have solved the problem by installing version 3.2.
Thank you again.
