### ISSUE TITLE
cannot render colour on atoms

### ISSUE THREAD

**Issue by liuyun88** [beautiful-atoms/beautiful-atoms#205]
**Describe the bug**
In the latest version of blender (4.0) and batoms, the colour of the atoms within the crystal unit cell are always rendered white. The atoms just outside of the unit cell are rendered correctly. The issue does not exist in the released version 2.3 of batoms in blender 3.6

**To Reproduce**
Run the attached sample python script.

**Expected behavior**
In Blender 3.6 and batoms 2.3, this is the rendered image.
![blender3 6_batoms_2 3](https://github.com/beautiful-atoms/beautiful-atoms/assets/8712609/f920373a-b66f-49c2-a9a0-c1e8343c01f6)

**Screenshots**
In Blender 4.0 and latest batoms, this is the rendered image
![blender4_batoms_latest](https://github.com/beautiful-atoms/beautiful-atoms/assets/8712609/cc86bac5-5fe9-450a-a955-aa95ff439b2c)

**Desktop:**
Linux, Debian 12

**Blender Version**
- 4.0

**Here is the sample script**
`from ase.io import read
from batoms import Batoms
from batoms.draw import draw_plane
from batoms.utils.butils import removeAll, set_world

removeAll()
gan = read('/home/user/scripts/batoms/POSCAR', format='vasp')
gan = Batoms(label='perovskite', from_ase=gan, color_style="1")
gan['Ga'].materials = {'Base Color': [0.055, 1, 0.725, 1.0]}
gan['N'].materials = {'Base Color': [0.56, 0.12, 0.54, 1.0]}
gan.boundary = 0.01
set_world(color = [1.0, 1.0, 1.0, 0.2])
gan.render.viewport = [0.3, 1, 0.3]
gan.render.engine = 'cycles'
gan.bond.settings[('Ga', 'N')].search = 1
gan.bond.settings[('Ga', 'N')].width = 0.05
gan.polyhedra.settings['Ga'].color = [0.5, 0.5, 0.5, 0.5]
gan.model_style = 1
gan['Ga'].scale = 0.5
gan['N'].scale = 0.5
gan.get_image(output = '/home/user/scripts/batoms/new.png')`

**Comment by superstar54** [comment]
Thanks for reporting the issue.
I did a quick test in Blender 4.0.1 and used the latest batoms. The color works fine.
<img width=300 src=https://github.com/beautiful-atoms/beautiful-atoms/assets/11457659/80d27afb-e5e9-415e-ac27-b52113ee640a >

Could you run your Python codes inside Blender's Python console, what color looks like there?

**Comment by liuyun88** [comment]
The python code was run inside the Python console, with Blender 4.0.1.

**Comment by superstar54** [comment]
What does the color look like there in the 3D viewer of Blender? On the top right corner of the 3D viewer, please choose `viewpoint Shading`


![Screenshot from 2023-12-05 10-26-27](https://github.com/beautiful-atoms/beautiful-atoms/assets/11457659/120fec3d-0015-4250-bb3d-f5f55a423278)

**Comment by superstar54** [comment]
Hi @liuyun88 , Yes, you are right, this is a bug. This is fixed in the latest batoms. Please try.

**Comment by liuyun88** [comment]
Great it works fine now. Thanks for the quick fix.
