### ISSUE TITLE
model_style = 1 for FeN4 2d material

### ISSUE THREAD

**Issue by YukeLi-chem** [beautiful-atoms/beautiful-atoms#207]
The single atom catalyst FeN4 is loaded in the beautiful atoms.  
enclosed please find the my FeN4.vasp 
[FeN4.zip](https://github.com/beautiful-atoms/beautiful-atoms/files/14203551/FeN4.zip)
file.

The python script:
[from ase.io import read
from batoms import Batoms
from batoms.draw import draw_plane
from batoms.utils.butils import removeAll, set_world
removeAll()

name="FeN4.vasp"
atoms = read(name)
mof = Batoms(label='mof-5', from_ase=atoms)
mof.model_style = 1
##########

The error:
IndexError: index -9999 is out of bounds for axis 1 with size 3.

**Comment by superstar54** [comment]
Beautiful atoms has a [Search bond mode](https://beautiful-atoms.readthedocs.io/en/latest/tutorial/bond_polyhedra.html#search-bond-mode), which will search the "C-C" bond recursively outside the unit cell, to find the C chain of a molecule. In your system, this will be a infinite large.

You can disable the searching.
```
# disable C-C bond searching
mof.bond.settings['C-C'].search = 1
mof.model_style = 1
```

**Comment by YukeLi-chem** [comment]
It works, Thanks.

**Comment by superstar54** [comment]
Welcome!
