### ISSUE TITLE
More color style

### ISSUE THREAD

**Issue by superstar54** [beautiful-atoms/beautiful-atoms#46]
Currently, batoms set the color of atoms by elements.

To add more color styles:

1) single color
2) random color
3) by other tags (positions, charge ...)

**Comment by nilsholle** [comment]
Hi, is there any news on this idea? It could indeed be very useful.

**Comment by superstar54** [comment]
Hi, currently, you can use `species` to achieve this. Please see this: https://beautiful-atoms.readthedocs.io/en/latest/tutorial/species.html#species

There is another more advanced method (not implemented yet), which is to use the `realize instances node`.

**Comment by nilsholle** [comment]
Ok, thanks!

**Comment by superstar54** [comment]
@nilsholle The latest version now supports color atoms by their attributes (e.g., positions, charges). Please check: https://beautiful-atoms.readthedocs.io/en/latest/tutorial/color.html#color-by-attributes
